
INSERT INTO dbo.MARCA(IDMARCA,NOMBRE) VALUES(1,'PERU');
INSERT INTO dbo.MARCA(IDMARCA,NOMBRE) VALUES(2,'TOYOTA');
INSERT INTO dbo.MARCA(IDMARCA,NOMBRE) VALUES(3,'NISSAN');
GO

SELECT * FROM DBO.MARCA;
GO


INSERT INTO DBO.AUTO(IDAUTO,IDMARCA,NROSERIE,MODELO,PRECIO,VENDIDO)
VALUES(1,2,'324576','MODELO SONICO',60345.00,0);
GO

INSERT INTO DBO.AUTO(IDAUTO,IDMARCA,NROSERIE,MODELO,PRECIO,VENDIDO)
VALUES(2,2,'76892345','MODELO SONICO',60345.00,0);
GO

INSERT INTO DBO.AUTO(IDAUTO,IDMARCA,NROSERIE,MODELO,PRECIO,VENDIDO)
VALUES(3,1,'67567657','MODELO ALPHA',70341.00,0);
GO

/*
CONSTRAINT FK_AUTO_MARCA FOREIGN KEY (IDMARCA) REFERENCES dbo.MARCA(IDMARCA)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
*/

DELETE FROM DBO.MARCA WHERE IDMARCA = 2;
GO

DELETE FROM DBO.MARCA WHERE IDMARCA = 3;
GO

-- CHECK

INSERT INTO DBO.AUTO(IDAUTO,IDMARCA,NROSERIE,MODELO,PRECIO,VENDIDO)
VALUES(4,1,'7488899934','MODELO ALPHA',-70341.00,0);
GO

